### ISSUE TITLE
Добавить все видео с митапов в каталог PyVideo.org

### ISSUE THREAD

**Issue by shurph** [minskpython/ideas-and-proposals#3]
_Уже давно стоит вопрос о том, что нужно какое-то «searchable» хранилище для видеозаписей, которые сейчас хостятся на ютубе (см. обсуждение в https://github.com/minskpython/videos/issues/1)_.

Однако, в качестве такого хранилища может выступать сайт [pyvideo.org](https://pyvideo.org). Товарищи из pyvideo готовы принимать видео c Minsk Python Meetup в свой каталог: https://github.com/pyvideo/data/issues/911.

**Задача**

Нужно, следуя инструкциям из https://github.com/pyvideo/data/issues/911, достать мета-информацию о видео с youtube-канала Minsk Python Meetup и отправить эту информацию в yaml формате в репозиторий https://github.com/pyvideo/data.

В идеале, это следует сделать с ручным редактированием мета-информации в тех местах, где это нужно (см. подробности в комментариях к ишью https://github.com/pyvideo/data/issues/911).
Однако, для первого шага может быть достаточно режима `minimal_download`.

**Comment by miksask** [comment]
Немного о **мотивации** (зачем это нужно):

Добавление всех видео в общий каталог pyvideo может _дать следующую **пользу**_:
- улучшит «поискабельность» видеозаписей
- увеличит видимость минского python сообщества на мировой арене python сообществ :-)
- «запромоутит» видеозаписи выступлений и само сообщество среди тех, кто ищет новый видео-материал по python через pyvideo
- даст удобный, машиночитаемый, список всех видеозаписей, который можно будет дальше использовать в какой-то автоматизации, например:
  - локальное бекапирование видеозаписей
  - бекапирование видеоазписей на других видеохостингах (vimeo и т.п.)

**Comment by miksask** [comment]
Дополнительно, было бы неплохо собирать мета информацию о каждом видео с Ютуба:
- количество просторов
- количество лайков/дизлайков
- количество комментариев

**Comment by karelin** [comment]
Возможно, здесь есть полезный код для старта: https://github.com/youtube/api-samples/blob/master/python/video_localizations.py

**Comment by miksask** [comment]
DONE: https://github.com/pyvideo/data/pull/954
